// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeHC8SxKWsN7aTY7ZqxNcpyQF0OQD4d5g',
    appId: '1:449854355808:web:54142f85af7daab01c8605',
    messagingSenderId: '449854355808',
    projectId: 'dashchat-e9def',
    authDomain: 'dashchat-e9def.firebaseapp.com',
    storageBucket: 'dashchat-e9def.appspot.com',
    measurementId: 'G-7QD7GMJHC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYzvomCpoUdHueSzwWm8CxGetnWoXQ06M',
    appId: '1:449854355808:android:4812ef694783b0541c8605',
    messagingSenderId: '449854355808',
    projectId: 'dashchat-e9def',
    storageBucket: 'dashchat-e9def.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAij5EXfkbYxJjnBtDCUDaLKi4Qiahfw8M',
    appId: '1:449854355808:ios:9738c77313c5eb6a1c8605',
    messagingSenderId: '449854355808',
    projectId: 'dashchat-e9def',
    storageBucket: 'dashchat-e9def.appspot.com',
    iosClientId: '449854355808-4h114ci2ikj5kq85q28bihdiu6gt5q45.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAij5EXfkbYxJjnBtDCUDaLKi4Qiahfw8M',
    appId: '1:449854355808:ios:36cb20332e6f55631c8605',
    messagingSenderId: '449854355808',
    projectId: 'dashchat-e9def',
    storageBucket: 'dashchat-e9def.appspot.com',
    iosClientId: '449854355808-ib14clnn068b4g64kuvid88mbkcc01sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashchat.RunnerTests',
  );
}
